### ISSUE TITLE
Testing the external validation of a model containing stratification

### ISSUE THREAD

**Issue by crystianbso** [GlenMartin31/predRupdate#15]
**Describe the bug**
Dear {predRupdate} team, 

I have a prediction model that was created containing four predictors and another variable which was used as a stratification variable. My aim is to investigate the external validation of this model using a new sample. I have included all the predictors of the new sample as the new_data including the stratification variable (that is, pain (see the screenshot below). However, I'm not quite sure how to include this stratification variable in the {pred_input_info} or in the {pred_validate}. These were the commands that I used without the stratification variable: 

coefs_table <- data.frame("change" = 0.31644,
                          "previous" = -0.07831,
                          "duration" = -0.12918,
                          "depressao" = -0.16246)
Existing_TTE_Model <- pred_input_info(model_type = "survival",
                                      model_info = coefs_table,
                                      cum_hazard = NULL)
data <- read.csv("external_data.csv",sep=',')
validation_results <- pred_validate(x = Existing_TTE_Model,
                                    new_data = data,
                                    survival_time = "time",
                                    event_indicator = "event",
                                    time_horizon = 3)

**Expected behavior**
I was able to have the calibration slope to this model, but I believe that the results would be different when including the stratification variable: 

Calibration Measures 
--------------------------------- 
                        Estimate Std. Err Lower 95% Confidence Interval
Observed:Expected Ratio       NA       NA                            NA
Calibration Slope        -0.5715   0.2906                       -1.1411
                        Upper 95% Confidence Interval
Observed:Expected Ratio                            NA
Calibration Slope                              -0.002

 Also examine the calibration plot, if produced. 

Discrimination Measures 
--------------------------------- 
          Estimate Std. Err Lower 95% Confidence Interval
Harrell C   0.4387   0.0312                        0.3775
          Upper 95% Confidence Interval
Harrell C                        0.4999

 Also examine the histogram of predicted risks.

**Screenshots**
This is the screenshot of the dataframe (new_data):

<img width="501" alt="image" src="https://github.com/GlenMartin31/predRupdate/assets/146389816/22ee1448-b1df-4050-98cd-fc9252836f73">

**Desktop (please complete the following information):**
 - OS

**Additional context**
Thanks for the help. 
Cheers.

**Comment by GlenMartin31** [comment]
Hi, many thanks for your comments and questions. 

When you say stratification variable, I take this as meaning that the baseline hazard of the model being validated was stratified by the 'pain' variable. 

If so, then the calibration slope of this model, estimated over the entire population of new_data, will be the same with or without incorporating the stratification variable, because this assesses the linear predictor (each log hazard ratio multiplied by the corresponding covariate in new_data) of the model in new_data, which will be the same for everyone (since the stratification only affects the baseline hazard). 

To incorporate the stratification variable, you would need to incorporate this into the `cum_hazard` argument of `pred_input_info()`. Currently, the only way to do this would be to create separate `pred_input_info()` objects for each strata of 'pain' variable (passing in the relevant cumulative baseline hazard for each strata). You would then use `pred_validate()` within subsets of the 'pain' variable to estimate the performance of the model within each strata. 

Hope that helps. 

Best wishes
Glen
